---
- name: Get docker command
  shell: command -v docker
  register: docker_command
  ignore_errors: yes

- debug: var=docker_command.stdout

- name: Download get-docker.sh
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: +x
  when: docker_command.stdout == ''

- name: Run get-docker.sh
  become: yes
  shell: /tmp/get-docker.sh
  register: get_docker
  when: docker_command.stdout == ''

- debug: var=get_docker
  when: docker_command.stdout == ''

- name: Add pi to docker group
  become: yes
  user:
    name: pi
    groups: docker
    append: yes
  notify: reboot

