---
- name: Openbox Configuration
  become: yes
  blockinfile:
    path: /etc/xdg/openbox/autostart
    block: |
      # Disable any form of screen saver / screen blanking / power management
      xset s off
      xset s noblank
      xset -dpms

      # Hide cursor after 0.5s
      unclutter -idle 0.5 -root &

      # Start electron app
      npm run --prefix {{deploy_directory}}/electron start
  notify: reboot
